name: CI
on: [pull_request, workflow_dispatch]
jobs:
  tests:
    name: Code style and execute unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: python3 -m pip install -r tests-requirements.txt
      - name: Run tests
        shell: bash
        run: ./run-tests.sh
